### ISSUE TITLE
Undefined control sequence  \AtBeginShipoutOriginalShipout

### ISSUE THREAD

**Issue by PaulPichaureau** [ho-tex/atbegshi#1]
Hi,

I used atbegshi for a while, but right now I have this very strange error, with the following MWE :

```
\documentclass{article}

\usepackage{atbegshi}

\AtBeginShipout{test}%

\begin{document}
\AtBeginShipoutOriginalShipout
$\sin x$
\end{document}
```

The error:

```
(./test.aux)
! Undefined control sequence.
l.10 \AtBeginShipoutOriginalShipout
                                   
? x
No pages of output.
Transcript written on test.log.
```

Any clue of what's going wrong?

My Platform: MacOs 11.0.1 / MacTeX / pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)

**Comment by davidcarlisle** [comment]
`\AtBeginShipoutOriginalShipout` was used as a "saved" name of the original `\shipout` command in the original atbegshi implementation, but it wasn't intended to be called directly, just used in the package internals. It isn't used in the new implementation, you could probably use `\shipout`  but it depends on the use case, how were you using this command?

**Comment by PaulPichaureau** [comment]
I'm using the command in a style file, to insert blank page (following an answer of this question [Add blank/empty page after every page automatically](https://tex.stackexchange.com/questions/409249/add-blank-empty-page-after-every-page-automatically) ).

When I replace `\AtBeginShipoutOriginalShipout` with `\shipout` it seems that I encounter an infinite loop (error message `! TeX capacity exceeded, sorry [input stack size=5000].`).

How can I simply shipout a page now?

**Comment by davidcarlisle** [comment]
Thanks for the test file, we will probably improve the atbegshi emulation to cover this, the following file works in both old and new releases, but may not be the fix we finally use. (I will ping here later if we update the base latex code.) Note the code change would need to be in the base latex release emulation of atbegshi, not in this repository. 

```

\documentclass{article}
\usepackage{atbegshi}


\AtBeginShipoutFirst{%
  \AtBeginShipout{%
    \ifx\AtBeginShipoutOriginalShipout\undefined
      \csname tex_shipout:D\endcsname
     \else
      \AtBeginShipoutOriginalShipout
    \fi\null
  }%
}

\usepackage{blindtext}
\begin{document}
\blinddocument
\end{document}
```

**Comment by PaulPichaureau** [comment]
Thank you, this code works perfectly.

**Comment by u-fischer** [comment]
This should better stay open until there is a real solution. The work-around is not something that should be used for long.

**Comment by davidcarlisle** [comment]
@PaulPichaureau  I agree with Ulrike we should leave it open. Note however if we improve the emulation of atbegshi so that itdefines `\AtBeginShipoutOrighinalShipout` the workaround suggested above will not do any harm (it will just do nothing and revert to using the command as before)

**Comment by car222222** [comment]
@PaulPichaureau But looking again at your original question on tex.sx, whilst Heiko's solution works, it is maybe not the best, of the many methods, to solve your problem.

Shipping out an empty box may not be the best way to do most things and it is almost certainly not an optimal way to fool your printer!
