### ISSUE TITLE
How to excute commands in limited areas

### ISSUE THREAD

**Issue by JohnsonLo00** [ho-tex/atbegshi#2]
Hi,
I intended to use *atbegshi* package to **insert a blank page after every page**.

It worked with the following codes ([source](https://tex.stackexchange.com/questions/409249/add-blank-empty-page-after-every-page-automatically) is here) for the case of the whole file:
```
\documentclass{article}
\usepackage{lipsum}
\usepackage{atbegshi}
\AtBeginShipoutFirst{%
  \AtBeginShipout{%
    \AtBeginShipoutOriginalShipout\null
  }%
}
\begin{document}
\lipsum
\end{document}
```

When it comes to the case of limited areas in this file, however, I cannot find an appropriate solution for it. For example, let it runs in pages of texts generated by `\lipsum` and stops before `abstract` environment, that is,
```
\documentclass{article}
\usepackage{lipsum}
\usepackage{atbegshi}
\AtBeginShipoutFirst{%
  \AtBeginShipout{%
    \AtBeginShipoutOriginalShipout\null
  }%
}
\begin{document}
\lipsum

% stop here

\begin{abstract}
% contents of abstract.
\end{abstract}
\end{document}
```

Any guidance is appreciated.

**Comment by davidcarlisle** [comment]
Note this is a bug report channel, tex.stackexchange or similar would be a better forum for such questions.

The package should not be used at all for new documents, it is a legacy interface, for new code you would be better to use latex's own shipout hooks (see `texdoc ltshipout-doc`)

either way though, a simple mechanism to add different code in different places is to simply put a single command say `\mypagecode`  into the hook and leave it there, then you can use a simple `\renewcommand` to change the meaning of `\mypagecode` from adding a page or doing nothing.

**Comment by JohnsonLo00** [comment]
Got it. Thanks a lot.
