### ISSUE TITLE
One possible CONFLICT between `\AtBeginShipout-` and `\addcontentsline`

### ISSUE THREAD

**Issue by JohnsonLo00** [ho-tex/atbegshi#3]
I intended to apply package `atbegshi` to insert one blank page after every current page by the following codes:
```latex
\documentclass{article}
\usepackage{lipsum}
\usepackage{atbegshi}
\usepackage{hyperref}

\newif\ifactivate
\activatefalse
% one hook to insert one blank page after every page
\AtBeginShipout{%
  \ifactivate
    \AtBeginShipoutOriginalShipout\box\AtBeginShipoutBox % to print the current page
    \AtBeginShipoutOriginalShipout\null % to print one blank page
  \fi
}

\begin{document}

\activatetrue
\begin{abstract}
\phantomsection
\addcontentsline{toc}{section}{ABSTRACT}
\lipsum[1-15]
\end{abstract}
\activatefalse

\tableofcontents

\section{Main Parts}

\end{document}
```

And it returned an error with the following message:
```
! Use of \@item doesn't match its definition.
\@ifnextchar ... \reserved@d =#1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
```

However, It ran without any error when I deleted the following two lines of code:
```
\phantomsection
\addcontentsline{toc}{section}{ABSTRACT}
```

Is there an conflict about command `\addcontentsline` ?

**Comment by u-fischer** [comment]
As David already wrote in your previous issue, atbegshi is obsolete. If you look into your log-file you will see that it is actually no longer loaded in a current LaTeX, instead atbegshi-ltx.sty is used which is a emulation of atbegshi.

Using the LaTeX hooks directly your code looks like this, and this compiles:

~~~~
\documentclass{article}
\usepackage{lipsum}
\usepackage{hyperref}

\newif\ifactivate
\activatefalse
% one hook to insert one blank page after every page
\AddToHook{shipout/before}{%
  \ifactivate
    \RawShipout\box\ShipoutBox % to print the current page
    \RawShipout\null % to print one blank page
  \fi
}

\begin{document}

\activatetrue
\begin{abstract}
\phantomsection
\addcontentsline{toc}{section}{ABSTRACT}
\lipsum[1-15]
\end{abstract}

\clearpage
\activatefalse

\tableofcontents

\section{Main Parts}

\end{document}
~~~~

 That said, I think the emulation is wrong in one place. With the following your code compiles too:
 
~~~~
\ExplSyntaxOn
\cs_set_eq:NN \AtBeginShipoutOriginalShipout \RawShipout
\ExplSyntaxOff
~~~~

**Comment by JohnsonLo00** [comment]
> That said, I think the emulation is wrong in one place. With the following your code compiles too:
> ```latex
> \ExplSyntaxOn
> \cs_set_eq:NN \AtBeginShipoutOriginalShipout \RawShipout
> \ExplSyntaxOff
> ```

It would result in inserting **two** blank pages instead of one blank page after every current page.

**Comment by u-fischer** [comment]
Right. And actually your code errors with the original atbegshi too. Your use of the original page is imho wrong and even without the addcontentsline and hyperref it produces warnings:
~~~~
Package atbegshi Warning: Shipout box was voided by hook,
(atbegshi)                ignoring shipout box on input line 55.

Package atbegshi Info: Shipout page discarded.
~~~~


With the original atbegshi you probably need to add the empty page before the next shipout with something like 
~~~~
\AtBeginShipout{%
 \ifactivate
  \AtBeginShipoutNext{\AtBeginShipoutOriginalShipout\null}%
 \fi   
}
~~~~

Better use the answer from tex.sx https://tex.stackexchange.com/a/733761/2388
